project:
  type: book
  resources: static/*
  output-dir: ../_docs
  lib-dir: libs/
  # pre-render: 
  # post-render:
 
format:
  html:
    theme:
      - cosmo
    css: libs/styles_20240812.2.css
    code-copy: true
    code-link: true
    
#bibliography: references.bib
#csl: harvard-cite-them-right-11th-edition.csl
#link-citations: true

# nocite: |
#   @*

book:
  title: "ECHILD Phenotype Code List Repository"
  reader-mode: true
  navbar:
    search: true
  page-footer: >
    The content of this site is licensed under the
    [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license](https://creativecommons.org/licenses/by-nc-sa/4.0/),
    except example source code which is provided under the
    [MIT license](https://github.com/UCL-ECHILD/code.echild.ac.uk-website/blob/main/LICENSE.md).
  # cover-image: cover.jpg
  # favicon: favicon.ico
  site-url: https://code.echild.ac.uk/
  repo-url: https://github.com/UCL-ECHILD/code.echild.ac.uk-website
  repo-subdir: web_source/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - primer.qmd
    - principles.qmd
    - usingscripts.qmd
    - howtosubmit.qmd
    - acknowledgements.qmd
    
