# 	Chronic health conditions - Hardelid {.unnumbered}

## Repository details

| | |
|---|---|
| **Name** | Chronic health conditions - Hardelid |
| **Version** | 1 |
| **id** | chc_hardelid_v1 |
| **Previous version(s)** | NA |
| **Number of files ** | 1 |
| **Code list file ** | [chc_hardelid_v1.csv](https://github.com/UCL-ECHILD/phenotype-code-lists/raw/main/chc_hardelid_v1.csv) |
| **Restrictions file ** | NA |
| **Truncations file ** | NA |
| **Removals file ** | NA |
| **R script** | |
| **Stata do file** | |
| **Prepared for repo by** | Matthew Jay |
| **First check** | Matthew Jay - 2024/06/19 |
| **Second check** | |
| **Date added** | 2024/06/19 |


## Background information

| | |
|---|---|
| **Authors** | Hardelid et al |
| **Year** | 2014 |
| **Reference** | [Hardelid P, et al. BMJ Open 2014;4:e005331](https://bmjopen.bmj.com/content/4/8/e005331){target="_blank"} |
| **Target phenotype** | Chronic health conditions |
| **Dataset** | HES APC |
| **Datafields** | diag |
| **Summary** | ICD-10 codes to identify chronic health conditions, defined as any health problem likely to require follow-up for more than 1 year, where follow-up could be repeated hospital admission, specialist follow-up through outpatient department visits, medication or use of support services. |
| **Validation** | Reference to ICD-10, previous code lists and hospital discharge data. Face validity assessed in consultations with clinical colleagues. |
| **Original purpose** | To describe what chronic health conditions die with, using HES APC as well as death certificates. |
| **Groups** | Nine groups according to body systems plus further sub-groups. |
| **Flags** | LOS3 = code is only valid if the admission is at least 3 days or longer. AGE10 = code is only valid if the child is aged 10 or older when the code was recorded. |
| **Other details** | NA |
| **Changes since first version** | NA |
| **Number of codes** | 1371 |
| **Codes removed** | 0 |
| **Codes truncated** | 0 |

## Preview

